Repository DIT113-V22/group-13, pull requests merged in 2022-04, with the labels that each got.

#18 Basic car mobility by accelerating and decelerating
  arduino/smartcar/smartcar.ino
Labels: Sprint #1

#19 car now drives backwards
  arduino/smartcar/smartcar.ino
Labels: Sprint #1

#20 Car can now turn when moving
  arduino/smartcar/smartcar.ino
Labels: Sprint #1

#21 Update ReadMe to set software for GUI
  README.md
Labels: documentation

#22 #16 Car can rotate when standing still
  arduino/smartcar/smartcar.ino
Labels: Sprint #1

#23 Add Application For Car Control
  .DS_Store
  CarControl/.gitignore
  CarControl/app/.gitignore
  CarControl/app/build.gradle
  CarControl/app/proguard-rules.pro
  CarControl/app/src/androidTest/java/com/code/carcontrol/ExampleInstrumentedTest.java
  CarControl/app/src/main/AndroidManifest.xml
  CarControl/app/src/main/java/com/code/carcontrol/Game.java
  CarControl/app/src/main/java/com/code/carcontrol/GameLoop.java
  CarControl/app/src/main/java/com/code/carcontrol/Joystick.java
  CarControl/app/src/main/java/com/code/carcontrol/MainActivity.java
  CarControl/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  CarControl/app/src/main/res/drawable/ic_launcher_background.xml
  CarControl/app/src/main/res/layout/activity_main.xml
  CarControl/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  CarControl/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  CarControl/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  CarControl/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  CarControl/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  CarControl/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  CarControl/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  CarControl/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  CarControl/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  CarControl/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  CarControl/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  CarControl/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  CarControl/app/src/main/res/values-night/themes.xml
  CarControl/app/src/main/res/values/colors.xml
  CarControl/app/src/main/res/values/strings.xml
  CarControl/app/src/main/res/values/themes.xml
  CarControl/app/src/test/java/com/code/carcontrol/ExampleUnitTest.java
  CarControl/build.gradle
  CarControl/gradle.properties
  CarControl/gradle/wrapper/gradle-wrapper.jar
  CarControl/gradle/wrapper/gradle-wrapper.properties
  CarControl/gradlew
  CarControl/gradlew.bat
  CarControl/org.eclipse.paho.client.mqttv3-1.2.5.jar
  CarControl/settings.gradle
Labels: User story, Sprint #1

#28 Implement CI + unit testing for the android App
  .github/workflows/Android-Build-&-Test.yml
Labels: CI, Android

#29 Create pull request template
  .github/pull_request_template.md
Labels: enhancement

#47 #30 Add infrared sensors
  MQTT_Joystick_Car/MQTT_Joystick_Car.ino
Labels: User story, Sprint #2, Arduino

#48 #33 & character in a workflow filename
  .github/workflows/Android-Build-And-Test.yml
Labels: bug, CI

#49 Uploaded mods folder
  Spatial.zip
Labels: User story, Sprint #1

#50 Sensor provides distance data
  arduino/MQTT_Joystick_Car/MQTT_Joystick_Car.ino
Labels: User story, Sprint #2

#52 35 stop car when obstacle is detected
  .DS_Store
  CarControl/app/src/main/java/com/code/carcontrol/MainActivity.java
  arduino/.DS_Store
  arduino/MQTT_Joystick_Car/MQTT_Joystick_Car.ino
Labels: User story, Sprint #2, Arduino

#53 Create review-template.md
  .github/review-template.md
Labels: enhancement
